### ISSUE TITLE
DX: Reference to private repository

### ISSUE THREAD

**Issue by mikaelkundert** [wunderio/charts#52]
In https://github.com/wunderio/charts/tree/master/silta-cluster there's a description:

> This helm chart helps setting up resources for https://github.com/wunderio/silta-cluster

The repository link is private.

As `wunderio/charts` is public repository, it might be a good idea to refer/support repositories that are only public. If this chart is not needed otherwise than with `wunderio/silta-cluster`, then maybe this chart is not in the right repository?

**Comment by Jancis** [comment]
I changed the repo url at some point to https://github.com/wunderio/silta-cluster-tf, managed to run setup with terraform, but it turned out to be lacking so we do it manually.
