### ISSUE TITLE
GDPR Dump may generate real user data

### ISSUE THREAD

**Issue by mikaelkundert** [wunderio/charts#68]
GDPR dump is generating email addresses that actually may be in use.

For security reasons I suggest to specify a template for using commonly used "`/dev/null`" email addresses ending with `@example.com`.

This way we avoid a problem if we accidentally send mass-email to "random" persons while using real domains such as `@gmail.com` or `@yahoo.com` email addresses.

**Comment by Jancis** [comment]
Good point! We replaced the `email` with `safe_email` at some point, but i can't find the change now.

**Comment by Jancis** [comment]
https://github.com/wunderio/charts/blob/master/drupal/values.yaml#L347
