### ISSUE TITLE
Add silta vhost/releasename as environment variable

### ISSUE THREAD

**Issue by kirkkala** [wunderio/charts#84]
Could we have the host (`.Release.Name` ?) as environment variable to Silta, similar to how [SLT-415](https://github.com/wunderio/charts/commit/bb9324da56fb6f21bc67bdbffbb625bbce6168f4) added the `ENVIRONMENT_DOMAIN`

We could use that for the SFS API rabbitmq [AMQP_HOST](https://github.com/wunderio/client-fi-sfs-ovk-api/pull/43/files#diff-5361227d648c0b5dbbfb3ffd05f6b38bR26) and [RABBITMQ_DEFAULT_VHOST](https://github.com/wunderio/client-fi-sfs-ovk-api/pull/43/files#diff-5361227d648c0b5dbbfb3ffd05f6b38bR45)

**Comment by floretan** [comment]
Thanks for the suggestion. The commit above should do it.
